setup: |
  echo "🐊 Start to install dependencies ..."
  echo "🐊 Note: Will not install dependencies if available"
  cd systemsense && poetry install
  echo "🐊 ... Done installing dependencies"
---

# Checks on Files {{{

# perform checks on a file
- README.md:
    - description: Ensure that the README.md file exists in the GitHub repository
      check: ConfirmFileExists

# perform checks on a file
- systemsense/systemsense/main.py:
    - description: Ensure that the main.py file exists in the systemsense/systemsense/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for main.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in main.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 2
        exact: false
    - description: Create a sufficient number of single-line comments in main.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

# perform checks on a file
- systemsense/systemsense/benchmark.py:
    - description: Ensure that the benchmark.py file exists in the systemsense/systemsense/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for benchmark.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in benchmark.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 12
        exact: false
    - description: Create a sufficient number of single-line comments in benchmark.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 20
        exact: false

# perform checks on a file
- systemsense/systemsense/constants.py:
    - description: Ensure that the constants.py file exists in the systemsense/systemsense/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for constants.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in constants.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 5
        exact: false
    - description: Create a sufficient number of single-line comments in constants.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 4
        exact: false

# perform checks on a file
- systemsense/systemsense/detect.py:
    - description: Ensure that the detect.py file exists in the systemsense/systemsense/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for detect.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in detect.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 15
        exact: false
    - description: Create a sufficient number of single-line comments in detect.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 50
        exact: false

# perform checks on a file
- systemsense/systemsense/execute.py:
    - description: Ensure that the execute.py file exists in the systemsense/systemsense/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for execute.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in execute.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 1
        exact: false
    - description: Create a sufficient number of single-line comments in execute.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 10
        exact: false

# perform checks on a file
- systemsense/systemsense/util.py:
    - description: Ensure that the util.py file exists in the systemsense/systemsense/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for util.py
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Create a sufficient number of docstring (i.e., multiple-line) comments in util.py
      check: CountMultipleLineComments
      options:
        language: "Python"
        count: 3
        exact: false
    - description: Create a sufficient number of single-line comments in util.py
      check: CountSingleLineComments
      options:
        language: "Python"
        count: 5
        exact: false

# perform checks on a file
- writing/reflection.md:
    - description: Ensure that the reflection.md file exists in the writing/ directory
      check: ConfirmFileExists
    - description: Complete all TODOs, remove the TODO markers, and rewrite comments for the reflection
      check: MatchFileFragment
      options:
        fragment: TODO
        count: 0
        exact: true
    - description: Delete the 'Add Your Name Here' prompt in the reflection file
      check: MatchFileFragment
      options:
        fragment: "Add Your Name Here"
        count: 0
        exact: true
    - description: Retype the every word in the Honor Code pledge in reflection.md
      check: MatchFileFragment
      options:
        fragment: "I adhered to the Allegheny College Honor Code while completing this project."
        count: 3
        exact: true
    - description: Confirm that the markdown file has the correct number of headers
      check: CountMarkdownTags
      options:
        tag: heading
        count: 18
        exact: false
    - description: Confirm that the markdown file has the correct number of fenced code blocks
      check: CountMarkdownTags
      options:
        tag: code_block
        count: 5
        exact: false

# }}}

# Check Output {{{

# run a check
- description: Pass the checks in the test suite
  command: cd systemsense && poetry run task test

# run a check
- description: Pass the coverage minimum checks for the tests
  command: cd systemsense && poetry run task coverage

# run a check
- description: Pass the source code formatting checks run by ruff
  command: cd systemsense && poetry run task format

# run a check
- description: Pass the linting checks run by mypy
  command: cd systemsense && poetry run task mypy

# run a check
- description: Pass the linting checks run by pymarkdown
  command: cd systemsense && poetry run task markdownlint

# run a check
- description: Pass the undocumented function checks run by symbex
  command: cd systemsense && poetry run task symbex-documented

# run a check
- description: Pass the untyped function checks run by symbex
  command: cd systemsense && poetry run task symbex-typed

# }}}

# Program Output {{{

# run the program and confirm correct number of lines in the output
- description: Run the program and confirm the correct number of non-blank lines in the output
  check: CountCommandOutput
  options:
    command: "cd systemsense && poetry run systemsense"
    count: 10
    exact: false

# run the program and confirm correct number of lines in the output
- description: Run the program and confirm the correct number of non-blank lines in the output
  check: CountCommandOutput
  options:
    command: "cd systemsense && poetry run systemsense --help"
    count: 10
    exact: false

# run the program and confirm correct number of lines in the output
- description: Run the program and confirm the correct number of non-blank lines in the output
  check: CountCommandOutput
  options:
    command: "cd systemsense && poetry run systemsense systeminfo"
    count: 20
    exact: false

# }}}

# Commits {{{

# count number of commits in the GitHub repository
- description: Have at least a specific minimum of commits in repository
  check: CountCommits
  options:
    count: 10

# }}}
